//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public int ID_Wlasciciela { get; set; }
        public string Nr_Karty { get; set; }
        public System.DateTime Exp_date { get; set; }
        public int cvv2 { get; set; }
    }
}
