//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient_ARCH
    {
        public int ID { get; set; }
        public string Imię { get; set; }
        public string Nazwisko { get; set; }
        public string Pesel { get; set; }
        public string Nr_Dowodu { get; set; }
        public string Adres { get; set; }
        public string Urzadzenie_Mobilne { get; set; }
        public string login { get; set; }
        public string haslo { get; set; }
        public Nullable<System.DateTime> Data_Usuniecia { get; set; }
    }
}
