//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PBank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class P_BankowoscEntities : DbContext
    {
        public P_BankowoscEntities()
            : base("name=P_BankowoscEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Karta> Karta { get; set; }
        public virtual DbSet<Klient> Klient { get; set; }
        public virtual DbSet<Pracownik> Pracownik { get; set; }
        public virtual DbSet<exklienci> exklienci { get; set; }
        public virtual DbSet<expracownicy> expracownicy { get; set; }
        public virtual DbSet<klienci> klienci { get; set; }
        public virtual DbSet<pracownicy> pracownicy { get; set; }
        public virtual DbSet<Pracownik_ARCH> Pracownik_ARCH { get; set; }
        public virtual DbSet<Klient_ARCH> Klient_ARCH { get; set; }
    
        public virtual int Awans(string stanowisko, Nullable<int> id)
        {
            var stanowiskoParameter = stanowisko != null ?
                new ObjectParameter("stanowisko", stanowisko) :
                new ObjectParameter("stanowisko", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Awans", stanowiskoParameter, idParameter);
        }
    
        public virtual int Pracownik_Manage(string stanowisko, Nullable<int> id, Nullable<double> pensja)
        {
            var stanowiskoParameter = stanowisko != null ?
                new ObjectParameter("stanowisko", stanowisko) :
                new ObjectParameter("stanowisko", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var pensjaParameter = pensja.HasValue ?
                new ObjectParameter("pensja", pensja) :
                new ObjectParameter("pensja", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pracownik_Manage", stanowiskoParameter, idParameter, pensjaParameter);
        }
    
        public virtual int pay_manage(Nullable<int> id, Nullable<double> pensja)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var pensjaParameter = pensja.HasValue ?
                new ObjectParameter("pensja", pensja) :
                new ObjectParameter("pensja", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pay_manage", idParameter, pensjaParameter);
        }
    
        public virtual int zatrudnij(string imie, string nazwisko, string pesel, string stanowisko, Nullable<int> nr_komputera, Nullable<int> przelozony, Nullable<double> pensja, string login, string haslo)
        {
            var imieParameter = imie != null ?
                new ObjectParameter("imie", imie) :
                new ObjectParameter("imie", typeof(string));
    
            var nazwiskoParameter = nazwisko != null ?
                new ObjectParameter("nazwisko", nazwisko) :
                new ObjectParameter("nazwisko", typeof(string));
    
            var peselParameter = pesel != null ?
                new ObjectParameter("pesel", pesel) :
                new ObjectParameter("pesel", typeof(string));
    
            var stanowiskoParameter = stanowisko != null ?
                new ObjectParameter("stanowisko", stanowisko) :
                new ObjectParameter("stanowisko", typeof(string));
    
            var nr_komputeraParameter = nr_komputera.HasValue ?
                new ObjectParameter("nr_komputera", nr_komputera) :
                new ObjectParameter("nr_komputera", typeof(int));
    
            var przelozonyParameter = przelozony.HasValue ?
                new ObjectParameter("przelozony", przelozony) :
                new ObjectParameter("przelozony", typeof(int));
    
            var pensjaParameter = pensja.HasValue ?
                new ObjectParameter("pensja", pensja) :
                new ObjectParameter("pensja", typeof(double));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var hasloParameter = haslo != null ?
                new ObjectParameter("haslo", haslo) :
                new ObjectParameter("haslo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zatrudnij", imieParameter, nazwiskoParameter, peselParameter, stanowiskoParameter, nr_komputeraParameter, przelozonyParameter, pensjaParameter, loginParameter, hasloParameter);
        }
    
        public virtual int zwolnij(Nullable<int> id, Nullable<System.DateTime> data)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zwolnij", idParameter, dataParameter);
        }
    
        public virtual int zwolnij1(Nullable<int> id, Nullable<System.DateTime> data)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zwolnij1", idParameter, dataParameter);
        }
    
        public virtual int zwolnij2(Nullable<int> id, Nullable<System.DateTime> data)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zwolnij2", idParameter, dataParameter);
        }
    
        public virtual int zwolnij3(Nullable<int> id, Nullable<System.DateTime> data)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("data", data) :
                new ObjectParameter("data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zwolnij3", idParameter, dataParameter);
        }
    
        public virtual int zwolnienie(Nullable<int> id, Nullable<System.DateTime> date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("zwolnienie", idParameter, dateParameter);
        }
    
        public virtual int usun(Nullable<int> id, Nullable<System.DateTime> date)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dateParameter = date.HasValue ?
                new ObjectParameter("date", date) :
                new ObjectParameter("date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usun", idParameter, dateParameter);
        }
    
        public virtual int dodaj(string imie, string nazwisko, string pesel, string nr_dowodu, string adres, string urzadzenie_mobilne, string login, string haslo)
        {
            var imieParameter = imie != null ?
                new ObjectParameter("imie", imie) :
                new ObjectParameter("imie", typeof(string));
    
            var nazwiskoParameter = nazwisko != null ?
                new ObjectParameter("nazwisko", nazwisko) :
                new ObjectParameter("nazwisko", typeof(string));
    
            var peselParameter = pesel != null ?
                new ObjectParameter("pesel", pesel) :
                new ObjectParameter("pesel", typeof(string));
    
            var nr_dowoduParameter = nr_dowodu != null ?
                new ObjectParameter("nr_dowodu", nr_dowodu) :
                new ObjectParameter("nr_dowodu", typeof(string));
    
            var adresParameter = adres != null ?
                new ObjectParameter("adres", adres) :
                new ObjectParameter("adres", typeof(string));
    
            var urzadzenie_mobilneParameter = urzadzenie_mobilne != null ?
                new ObjectParameter("urzadzenie_mobilne", urzadzenie_mobilne) :
                new ObjectParameter("urzadzenie_mobilne", typeof(string));
    
            var loginParameter = login != null ?
                new ObjectParameter("login", login) :
                new ObjectParameter("login", typeof(string));
    
            var hasloParameter = haslo != null ?
                new ObjectParameter("haslo", haslo) :
                new ObjectParameter("haslo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dodaj", imieParameter, nazwiskoParameter, peselParameter, nr_dowoduParameter, adresParameter, urzadzenie_mobilneParameter, loginParameter, hasloParameter);
        }
    
        public virtual int wplac(Nullable<int> id, Nullable<double> kwota)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var kwotaParameter = kwota.HasValue ?
                new ObjectParameter("kwota", kwota) :
                new ObjectParameter("kwota", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("wplac", idParameter, kwotaParameter);
        }
    
        public virtual int wyplac(Nullable<int> id, Nullable<double> kwota)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var kwotaParameter = kwota.HasValue ?
                new ObjectParameter("kwota", kwota) :
                new ObjectParameter("kwota", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("wyplac", idParameter, kwotaParameter);
        }
    }
}
